# cloudbuild_prod.yaml (Trigger 2: Prod Deployment)
substitutions:
  _ENTRY_POINT: 'http_entry_point'
  _RUNTIME: 'python312'
  _PROD_REGION: 'asia-south1'

steps:
# 1. Deploy to PROD environment (Gated by Approval)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to PROD CF'
  args:
  - gcloud
  - functions
  - deploy
  - my-cf-app-prod # PROD Function Name
  - --gen2
  - --runtime=$_RUNTIME
  - --entry-point=$_ENTRY_POINT
  - --source=.
  - '--region=$_PROD_REGION'
  - --trigger-http
  - --allow-unauthenticated

# Define a default for the substitution variable
substitutions:
  _COMMIT_SHA: 'default'
