# cloudbuild.yaml (Trigger 1: Main CI/CD)
substitutions:
  _PROD_TRIGGER_NAME: 'prod-cf-approval-trigger'
  _ENTRY_POINT: 'http_entry_point'
  _RUNTIME: 'python312'
  _DEV_REGION: 'us-central1'
  _STAGE_REGION: 'us-central1'
  _PROD_REGION: 'asia-south1'

steps:
# 1. Deploy to DEV environment (Automatic)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to DEV CF'
  args:
  - gcloud
  - functions
  - deploy
  - my-cf-app-dev
  - --gen2
  - --runtime=$_RUNTIME
  - --entry-point=$_ENTRY_POINT
  - --source=.
  - --region=$_DEV_REGION
  - --trigger-http
  - --allow-unauthenticated

# 2. Deploy to STAGE environment (Automatic)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to STAGE CF'
  args:
  - gcloud
  - functions
  - deploy
  - my-cf-app-stage
  - --gen2
  - --runtime=$_RUNTIME
  - --entry-point=$_ENTRY_POINT
  - --source=.
  - --region=$_STAGE_REGION
  - --trigger-http
  - --allow-unauthenticated

# 3. Programmatically Trigger the PROD Approval Gate..
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Trigger PROD Approval'
  args:
  - gcloud
  - builds
  - triggers
  - run
  - $_PROD_TRIGGER_NAME # Targets the separate trigger
  - '--branch=main'
  - '--substitutions=_COMMIT_SHA=$COMMIT_SHA' # Passes source code revision
  - '--region=asia-south1' # Cloud Build trigger run command is global or its region.
# ... (your existing steps, substitutions, and images sections) ...

# This block MUST be at the top level, like this:
options:
  logging: CLOUD_LOGGING_ONLY

