# Define a substitution variable to hold the name of the Prod approval trigger
substitutions:
  _PROD_TRIGGER_NAME: 'prod-approval-trigger'

steps:
# 1. Build the container image (CI)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Image'
  args: ['build', '-t', 'gcr.io/temporal-parser-478606-d2/my-app:$COMMIT_SHA', '.']

# 2. Push the single image to Artifact Registry (CI)
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Image'
  args: ['push', 'gcr.io/temporal-parser-478606-d2/my-app:$COMMIT_SHA']

# 3. Deploy to DEV environment (CD - Automatic)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to DEV'
  args:
  - gcloud
  - run
  - deploy
  - my-app-dev
  - --image=gcr.io/temporal-parser-478606-d2/my-app:$COMMIT_SHA
  - --region=asia-south1 # Example Dev Region
  - --allow-unauthenticated # or specific authentication flags

# 4. Deploy to STAGE environment (CD - Automatic)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to STAGE'
  args:
  - gcloud
  - run
  - deploy
  - my-app-stage
  - --image=gcr.io/temporal-parser-478606-d2/my-app:$COMMIT_SHA # Corrected typo here
  - --region=asia-south1 # Example Stage Region
  - --allow-unauthenticated

# 5. Programmatically Trigger the PROD Approval Gate
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Trigger PROD Approval'
  args:
  - gcloud
  - builds
  - triggers
  - run
  - $_PROD_TRIGGER_NAME # Uses the trigger name defined above
  - '--branch=main'
  # Pass the built image SHA as a substitution variable to the Prod trigger
  - '--substitutions=_IMAGE_SHA=gcr.io/temporal-parser-478606-d2/my-app:$COMMIT_SHA'
  - '--region=asia-south1' # Cloud Build trigger run command requires the trigger region

# This section lists the images that Cloud Build expects to be pushed to Artifact Registry
images:
- 'gcr.io/temporal-parser-478606-d2/my-app:$COMMIT_SHA'

# These are top-level build configuration settings, correctly placed.
# Note: If you are using a Cloud Build Trigger, the 'serviceAccount' specified
#       here will be ignored in favor of the service account configured
#       directly on the trigger itself. However, the 'options' will be respected.
serviceAccount: 'projects/temporal-parser-478606-d2/serviceAccounts/136380032856-compute@developer.gserviceaccount.com'
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: GCS_ONLY # This addresses the error from the previous prompt (option b or c)
